// <auto-generated />
using HowitzerServer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HowitzerServer.Migrations
{
    [DbContext(typeof(HowitzerServerContext))]
    [Migration("20200427185350_InitialSeedData")]
    partial class InitialSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HowitzerServer.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.HasKey("CardId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            CardId = -10,
                            Name = "TestCard-10"
                        },
                        new
                        {
                            CardId = -9,
                            Name = "TestCard-9"
                        },
                        new
                        {
                            CardId = -8,
                            Name = "TestCard-8"
                        },
                        new
                        {
                            CardId = -7,
                            Name = "TestCard-7"
                        },
                        new
                        {
                            CardId = -6,
                            Name = "TestCard-6"
                        },
                        new
                        {
                            CardId = -5,
                            Name = "TestCard-5"
                        },
                        new
                        {
                            CardId = -4,
                            Name = "TestCard-4"
                        },
                        new
                        {
                            CardId = -3,
                            Name = "TestCard-3"
                        },
                        new
                        {
                            CardId = -2,
                            Name = "TestCard-2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
